### ISSUE TITLE
Blanket dependency

### ISSUE THREAD

**Issue by fcaneto** [jamesramsay/hercule#19]
There seems to be some dependency on blanket for non dev installs.
After a 'npm install -g hercule', running hercule throws:

module.js:338
    throw err;
          ^
Error: Cannot find module 'blanket'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/hercule/lib/main.js:5:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/hercule/lib/main.js:80:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by jamesramsay** [comment]
I believe this has been fixed in v0.2.2. Let me know if you're still having troubles.
