### ISSUE TITLE
TranscludeStream is broken when using example from documentation or either example gulpfile

### ISSUE THREAD

**Issue by evanslify** [jamesramsay/hercule#324]
When using TranscludeStream, an error would be thrown instantly for now. This is caused by f0d049c.
```
[14:47:51] Using gulpfile ~/Dev/Projects/Current/lian-jien-pm/mock/gulpfile.js
[14:47:51] Starting 'hercule'...
[14:47:51] Finished 'hercule' after 10 ms
undefined undefined
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at new Transcluder (/tmp/test/node_modules/hercule/lib/transclude-stream.js:53:92)
    at DestroyableTransform._transform (/tmp/test/gulpfile.js:13:27)
    at DestroyableTransform.Transform._read (/tmp/test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/tmp/test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/tmp/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/tmp/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/tmp/test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/tmp/test/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

**Comment by jamesramsay** [comment]
Thanks for bug report @evanslify. The documentation and example is indeed wrong. The first argument should be the source name.

In your gulpfile, you should change

```diff
if (file.isStream()) {
-   var transcluder = new hercule.TranscludeStream(options); 
+   var transcluder = new hercule.TranscludeStream(null, options); 
  file.contents = file.contents.pipe(transcluder);                                                               
  return callback(null, file);                                                                                   
}
```
