### ISSUE TITLE
Size limitation on linked local files

### ISSUE THREAD

**Issue by mdverde** [jamesramsay/hercule#370]
It seems there's a limitation on linked local files. I have one Data Structures file with more than 7,000 rows and I get this error:

```
C:\Users\x\AppData\Roaming\npm\node_modules\hercule\lib\transclude.js:177
      while ((streamContent = this.read()) !== null) {
                                   ^

RangeError: Maximum call stack size exceeded
    at DestroyableTransform.inputReadable (C:\Users\x\AppData\Roaming\npm\node_modules\hercule\lib\transclude.js:177:36)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (C:\Users\x\AppData\Roaming\npm\node_modules\hercule\node_modules\readable-stream\lib\_stream_readable.js:429:10)
    at emitReadable (C:\Users\x\AppData\Roaming\npm\node_modules\hercule\node_modules\readable-stream\lib\_stream_readable.js:423:65)
    at readableAddChunk (C:\Users\x\AppData\Roaming\npm\node_modules\hercule\node_modules\readable-stream\lib\_stream_readable.js:219:35)
    at DestroyableTransform.Readable.push (C:\Users\x\AppData\Roaming\npm\node_modules\hercule\node_modules\readable-stream\lib\_stream_readable.js:171:10)
    at DestroyableTransform.Transform.push (C:\Users\x\AppData\Roaming\npm\node_modules\hercule\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at DestroyableTransform.transclude (C:\Users\x\AppData\Roaming\npm\node_modules\hercule\lib\transclude.js:129:12)
    at C:\Users\x\AppData\Roaming\npm\node_modules\hercule\lib\transclude.js:293:25
```

Is it by design or it's a bug? If it's by design what's the max size of the file?

**Comment by jamesramsay** [comment]
@mdverde thanks for reporting this issue. This definitely isn't a designed limit.

I've reproduced the issue with a file of 10,000 rows.

**Comment by jamesramsay** [comment]
@mdverde I've released a patch (`hercule@4.0.1`) which should resolve the issue. Please let me know if it solves it for you 👍

**Comment by mdverde** [comment]
Great! I'll test it on monday, and I'll let you know. Thank you very much!

**Comment by mdverde** [comment]
Works like a charm! Thanks!
